Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,10 +17,21 @@ jobs:
           python-version: '3.8'
           
       - name: Install Package
+        id: set
+        continue-on-error: true
         run: |
           pip install chromedriver-binary-auto
           pip install selenium
           pip install -r requirements.txt
+          
+      - name: Error handling
+        if: ${{ steps.set.outcome == 'failure' }}
+        run: |
+          echo "Error handling"
+          curl -X POST https://api.github.com/repos/nao-riku/python-334-2/dispatches \
+               -H 'authorization: Bearer '${{ secrets.KEY }} \
+               --data '{"event_type": "Error handling"}'
+          exit 1
           
       - name: Run Python
         env:
